kafka-config:
  bootstrap-servers: 'kafka-2.kafka.default.svc.cluster.local:29092,kafka-1.kafka.default.svc.cluster.local:29092,kafka-0.kafka.default.svc.cluster.local:29092'
  topic-name: camel-topic
  topic-names-to-create:
    - camel-topic
  num-of-partitions: 3
  replication-factor: 3

retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  multiplier: 2.0
  maxAttempts: 3
  sleep-time-ms: 2000
